workspace(name = "bazel_rules_container_nodejs_example")

git_repository(
  name = "bazel_rules_container",
  remote = "https://github.com/guymers/bazel_rules_container.git",
  commit = "a21aff3897fa4fe9d980776ce42485eadd832ac0",
)

load("@bazel_rules_container//container:pull.bzl", "container_pull")

container_pull(
  name = "debian_jessie",
  registry = "http://localhost:5000",
  image_name = "debian",
  image_tag = "8.5",
  image_reference = "ffb60fdbc401b2a692eef8d04616fca15905dce259d1499d96521970ed0bec36",
)

NODEJS_VERSION = "6.2.1"
new_http_archive(
  name = "nodejs",
  url = "https://nodejs.org/dist/v" + NODEJS_VERSION + "/node-v" + NODEJS_VERSION + "-linux-x64.tar.xz",
  sha256 = "1027de8bd78ef2cba2baf5a676d54f185f9632324465cfd8572c3568ca6e1f64",
  build_file_content = "exports_files(['node-v" + NODEJS_VERSION + "-linux-x64'])",
)
