workspace(name = "bazel_rules_container_nodejs_example")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")
load("//versions:versions.bzl", "NODEJS_VERSION")

local_repository(
  name = "bazel_rules_container",
  path = __workspace_dir__ + "/../",
)

load("@bazel_rules_container//container:repositories.bzl", "repositories")
repositories()

load("@io_bazel_rules_docker//repositories:repositories.bzl", container_repositories = "repositories")
container_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")
container_deps()


#########

load("@io_bazel_rules_docker//container:container.bzl", "container_pull")

container_pull(
  name = "base",
  registry = "gcr.io",
  repository = "distroless/cc",
  digest = "sha256:0f5177f34bfc3634d1b4b2209c26afe445ee790bc2ad987864b61b181ef23aa4",
)

# Update to 20200803 for amd64 (debuerreotype 0.10)
http_file(
    name = "debian_buster",
    downloaded_file_path = "buster-slim-rootfs.tar.xz",
    urls = ["https://raw.githubusercontent.com/debuerreotype/docker-debian-artifacts/3503997cf522377bc4e4967c7f0fcbcb18c69fc8/buster/slim/rootfs.tar.xz"],
    sha256 = "b1fe295f97980407edb25366a6eb00cfb4f9d4576acde98bfb29c7827006dfac",
)

http_archive(
  name = "nodejs",
  url = "https://nodejs.org/dist/v" + NODEJS_VERSION + "/node-v" + NODEJS_VERSION + "-linux-x64.tar.xz",
  sha256 = "b79e02e48d0a1ee4cd4ae138de97fda5413542f2a4f441a7d0e189697b8da563",
  build_file_content = "exports_files(['node-v" + NODEJS_VERSION + "-linux-x64'])",
)
