filegroup(
    name = "incremental_load_template",
    srcs = ["incremental_load.sh.tpl"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_container_template",
    srcs = ["test_container.sh.tpl"],
    visibility = ["//visibility:public"],
)
