name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: bazel cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
        restore-keys: ${{ runner.os }}-${{ env.cache-name }}-master

    - name: bazel version
      run: bazel version

    - name: docs
      run: bazel build //docs/...

    - name: examples
      run: cd examples && ./ci.sh
